# Generated by Django 5.2.17 on 2026-09-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Deterministic SHA-256 or structured idempotency key', max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('instrument', models.CharField(db_index=True, default='XAUUSD', max_length=32)),
                ('display_symbol', models.CharField(default='XAU/USD', max_length=32)),
                ('candidate_state', models.CharField(default='NO_TRADE', max_length=32)),
                ('candidate_user_decision', models.CharField(default='WAIT', max_length=16)),
                ('published_state', models.CharField(default='NO_TRADE', max_length=32)),
                ('published_user_decision', models.CharField(default='WAIT', max_length=16)),
                ('side', models.CharField(blank=True, max_length=16, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('entry_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('entry_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('stop_final', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tp1', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('planned_rr_tp1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('analysis_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quote_timestamp', models.DateTimeField(blank=True, null=True)),
                ('analysis_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('risk_plan_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('calibration_status', models.CharField(default='CALIBRATION_REQUIRED', max_length=64)),
                ('hard_gate_reasons', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(default=dict, help_text='Full canonical JSON payload')),
                ('disclaimer', models.CharField(default='MANUAL DECISION SUPPORT ONLY — NO AUTO-ORDER EXECUTION.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'Dispatched'), ('SUPPRESSED', 'Suppressed by Safety Policy'), ('FAILED', 'Dispatch Failed'), ('DISABLED', 'Transport Disabled / Not Configured')], db_index=True, default='PENDING', max_length=32)),
                ('dispatch_attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'alert_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument', '-created_at'], name='alert_event_instrum_9efe4d_idx'), models.Index(fields=['event_type', 'status'], name='alert_event_event_t_0dc15e_idx')],
            },
        ),
    ]
