# Generated by Django 5.2.17 on 2026-08-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DISABLED', 'User Disabled'), ('USER_ENABLED', 'User Enabled'), ('ROLE_CHANGED', 'Role Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('PASSWORD_CHANGED', 'Password Changed')], db_index=True, max_length=32)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Management Audit Log',
                'verbose_name_plural': 'User Management Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
