# Generated by Django 5.2.17 on 2026-08-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ema20', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('ema50', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('ema200', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('ema_slope_20', models.FloatField(blank=True, null=True)),
                ('ema_alignment', models.SmallIntegerField(default=0)),
                ('adx', models.FloatField(blank=True, null=True)),
                ('plus_di', models.FloatField(blank=True, null=True)),
                ('minus_di', models.FloatField(blank=True, null=True)),
                ('rsi14', models.FloatField(blank=True, null=True)),
                ('macd_line', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('macd_hist', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('roc12', models.FloatField(blank=True, null=True)),
                ('atr14', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('atr_pct', models.FloatField(blank=True, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('bb_bandwidth', models.FloatField(blank=True, null=True)),
                ('realized_vol_20', models.FloatField(blank=True, null=True)),
                ('volume_ratio_20', models.FloatField(blank=True, null=True)),
                ('volume_zscore_20', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='analysis_fe_instrum_14e0e5_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='RegimeSnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('regime', models.CharField(db_index=True, max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regime_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='analysis_re_instrum_dd8f57_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StructureSnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('structure_type', models.CharField(max_length=32)),
                ('bos', models.CharField(max_length=16)),
                ('last_swing_high_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('last_swing_low_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('active_zones', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='analysis_st_instrum_07cec6_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
    ]
