# Generated by Django 5.2.17 on 2026-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresnapshotrecord',
            name='feature_version',
            field=models.CharField(db_index=True, default='feat-2026-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='regimesnapshotrecord',
            name='feature_version',
            field=models.CharField(db_index=True, default='feat-2026-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='structuresnapshotrecord',
            name='feature_version',
            field=models.CharField(db_index=True, default='feat-2026-v1', max_length=32),
        ),
    ]
