# Generated by Django 5.2.17 on 2026-08-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_featuresnapshotrecord_feature_version_and_more'),
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('session', models.CharField(db_index=True, max_length=32)),
                ('session_progress_pct', models.FloatField(default=0.0)),
                ('is_high_liquidity', models.BooleanField(default=False)),
                ('bars_since_last_swing', models.IntegerField(default=0)),
                ('pullback_age_percentile', models.FloatField(default=0.0)),
                ('is_mature_pullback', models.BooleanField(default=False)),
                ('is_blocked_by_event', models.BooleanField(default=False)),
                ('cycle_score_3a', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('cycle_version', models.CharField(db_index=True, default='3.0.0-3A', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='analysis_cy_instrum_09d40e_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
    ]
