# Generated by Django 5.2.17 on 2026-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_cyclesnapshotrecord'),
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cyclesnapshotrecord',
            name='analysis_cy_instrum_09d40e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cyclesnapshotrecord',
            unique_together={('instrument', 'timeframe', 'timestamp', 'cycle_version')},
        ),
        migrations.AlterField(
            model_name='cyclesnapshotrecord',
            name='pullback_age_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cyclesnapshotrecord',
            index=models.Index(fields=['instrument', 'timeframe', '-timestamp', 'cycle_version'], name='analysis_cy_instrum_93bdf2_idx'),
        ),
    ]
