# Generated by Django 5.2.17 on 2026-08-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_cyclesnapshotrecord_analysis_cy_instrum_09d40e_idx_and_more'),
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalCycleSnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('experimental_version', models.CharField(db_index=True, default='3.1.0-3B', max_length=32)),
                ('dominant_period_bars', models.FloatField(blank=True, null=True)),
                ('acf_dominant_lag', models.IntegerField(blank=True, null=True)),
                ('acf_correlation', models.FloatField(default=0.0)),
                ('fft_dominant_period', models.FloatField(blank=True, null=True)),
                ('fft_power_ratio', models.FloatField(default=0.0)),
                ('wavelet_dominant_period', models.FloatField(blank=True, null=True)),
                ('wavelet_energy_ratio', models.FloatField(default=0.0)),
                ('hilbert_phase', models.FloatField(default=0.0)),
                ('hilbert_stability', models.FloatField(default=0.0)),
                ('method_agreement_pct', models.FloatField(default=0.0)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('reliability_status', models.CharField(default='UNRELIABLE', max_length=32)),
                ('production_weight', models.FloatField(default=0.0)),
                ('promotion_status', models.CharField(default='BASELINE_NOT_EMPIRICAL', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_cycle_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp', 'experimental_version'], name='analysis_ex_instrum_e0cd6b_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp', 'experimental_version')},
            },
        ),
    ]
