# Generated by Django 5.2.17 on 2026-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_experimentalcyclesnapshotrecord'),
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='experimentalcyclesnapshotrecord',
            constraint=models.CheckConstraint(condition=models.Q(('production_weight', 0.0)), name='phase3b_production_weight_locked_to_zero'),
        ),
    ]
