# Generated by Django 5.2.17 on 2026-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_experimentalcyclesnapshotrecord_phase3b_production_weight_locked_to_zero'),
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='featuresnapshotrecord',
            name='analysis_fe_instrum_14e0e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='regimesnapshotrecord',
            name='analysis_re_instrum_dd8f57_idx',
        ),
        migrations.RemoveIndex(
            model_name='structuresnapshotrecord',
            name='analysis_st_instrum_07cec6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='featuresnapshotrecord',
            unique_together={('instrument', 'timeframe', 'timestamp', 'feature_version')},
        ),
        migrations.AlterUniqueTogether(
            name='regimesnapshotrecord',
            unique_together={('instrument', 'timeframe', 'timestamp', 'feature_version')},
        ),
        migrations.AlterUniqueTogether(
            name='structuresnapshotrecord',
            unique_together={('instrument', 'timeframe', 'timestamp', 'feature_version')},
        ),
        migrations.AddIndex(
            model_name='featuresnapshotrecord',
            index=models.Index(fields=['instrument', 'timeframe', '-timestamp', 'feature_version'], name='analysis_fe_instrum_a5f23e_idx'),
        ),
        migrations.AddIndex(
            model_name='regimesnapshotrecord',
            index=models.Index(fields=['instrument', 'timeframe', '-timestamp', 'feature_version'], name='analysis_re_instrum_3ac374_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresnapshotrecord',
            index=models.Index(fields=['instrument', 'timeframe', '-timestamp', 'feature_version'], name='analysis_st_instrum_e9cc85_idx'),
        ),
    ]
