# Generated by Django 5.2.17 on 2026-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_featuresnapshotrecord_analysis_fe_instrum_14e0e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresnapshotrecord',
            name='volume_evidence',
            field=models.CharField(blank=True, default='UNAVAILABLE', max_length=32),
        ),
        migrations.AddField(
            model_name='featuresnapshotrecord',
            name='volume_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='featuresnapshotrecord',
            name='volume_usable',
            field=models.BooleanField(default=False),
        ),
    ]
