# Generated by Django 5.2.17 on 2026-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_featuresnapshotrecord_volume_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclesnapshotrecord',
            name='calibration_artifact_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cyclesnapshotrecord',
            name='calibration_status',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cyclesnapshotrecord',
            name='profile_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
