# Generated by Django 5.2.17 on 2026-08-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('asset_type', models.CharField(choices=[('CRYPTO_TOKEN', 'Crypto Token'), ('COMMODITY', 'Physical Commodity'), ('FIAT', 'Fiat Currency'), ('INDEX', 'Financial Index')], default='CRYPTO_TOKEN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('SPOT', 'Spot Market'), ('FUTURES', 'Futures Contract'), ('INDEX', 'Market Index')], default='SPOT', max_length=16)),
                ('role', models.CharField(choices=[('EXECUTION', 'Execution Target (XAUT/USDT)'), ('GOLD_REFERENCE', 'Primary Gold Directional Reference (XAU/USD)'), ('GOLD_CONFIRMATION', 'Secondary Confirmation (Gold Futures)'), ('QUOTE_NORMALIZATION', 'Stablecoin Normalization Rate (USDT/USD)'), ('MACRO', 'Macro USD Filter (DXY / Yields)')], db_index=True, default='EXECUTION', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_instruments', to='instruments.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_instruments', to='instruments.asset')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['base_asset__code', 'quote_asset__code'],
                'unique_together': {('base_asset', 'quote_asset', 'instrument_type')},
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('provider_symbol', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HALTED', 'Trading Halted'), ('DELISTED', 'Delisted')], db_index=True, default='ACTIVE', max_length=16)),
                ('tick_size', models.DecimalField(decimal_places=6, default=0.01, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=6, default=0.0001, max_digits=12)),
                ('fallback_priority', models.IntegerField(default=0, help_text='Priority for failover ordering (0 = primary, 1 = secondary fallback, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Market Listing',
                'verbose_name_plural': 'Market Listings',
                'ordering': ['fallback_priority', 'provider'],
                'unique_together': {('instrument', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProviderHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('QUARANTINED', 'Quarantined'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='instruments.marketlisting')),
            ],
            options={
                'verbose_name': 'Provider Health Snapshot',
                'verbose_name_plural': 'Provider Health Snapshots',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['listing', '-checked_at'], name='instruments_listing_a0d70a_idx')],
            },
        ),
    ]
