# Generated by Django 5.2.17 on 2026-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='role',
            field=models.CharField(choices=[('PRIMARY_SIGNAL', 'Primary Signal Target (XAU/USD)'), ('PRIMARY_XAUUSD', 'Primary Signal Target (XAU/USD)'), ('SECONDARY_XAUUSD', 'Secondary Consensus Reference (XAU/USD)'), ('EXECUTION', 'Execution Target (XAUT/USDT)'), ('GOLD_REFERENCE', 'Canonical Gold Directional Reference (XAU/USD)'), ('GOLD_CONFIRMATION', 'Secondary Confirmation Proxy (PAXG / Gold Futures)'), ('QUOTE_NORMALIZATION', 'Canonical Stablecoin Normalization Rate (USDT/USD)'), ('QUOTE_NORMALIZATION_PROXY', 'Stablecoin Proxy Normalization Rate (USDT/USDC)'), ('MACRO', 'Macro USD Filter (DXY / Yields)')], db_index=True, default='EXECUTION', max_length=32),
        ),
    ]
