# Generated by Django 5.2.17 on 2026-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instrument_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='listing_role',
            field=models.CharField(choices=[('PRIMARY_XAUUSD_SPOT', 'Primary Spot XAU/USD Feed'), ('SECONDARY_XAUUSD_SPOT', 'Secondary Spot XAU/USD Consensus'), ('LEGACY_EXECUTION', 'Legacy Execution Feed (XAUT/USDT)'), ('LEGACY_GOLD_REFERENCE', 'Legacy Gold Reference (XAU/USD)'), ('LEGACY_QUOTE_NORMALIZATION', 'Legacy USDT Normalization Rate'), ('GENERIC', 'Generic Venue Listing')], db_index=True, default='GENERIC', help_text='Explicit source role for deterministic provider resolution', max_length=32),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='role',
            field=models.CharField(choices=[('EXECUTION', 'Execution Target (XAUT/USDT)'), ('GOLD_REFERENCE', 'Canonical Gold Directional Reference (XAU/USD)'), ('GOLD_CONFIRMATION', 'Secondary Confirmation Proxy (PAXG / Gold Futures)'), ('QUOTE_NORMALIZATION', 'Canonical Stablecoin Normalization Rate (USDT/USD)'), ('QUOTE_NORMALIZATION_PROXY', 'Stablecoin Proxy Normalization Rate (USDT/USDC)'), ('MACRO', 'Macro USD Filter (DXY / Yields)'), ('PRIMARY_SIGNAL', 'Primary Signal Target (XAU/USD)')], db_index=True, default='EXECUTION', max_length=32),
        ),
        migrations.AlterField(
            model_name='providerhealthsnapshot',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('QUARANTINED', 'Quarantined'), ('NOT_CONFIGURED', 'Not Configured'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
    ]
