# Generated by Django 5.2.17 on 2026-08-29 10:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(max_length=64)),
                ('quarantined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('basis_deviation', models.DecimalField(blank=True, decimal_places=4, help_text='Deviation percentage from consensus reference', max_digits=8, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='instruments.marketlisting')),
            ],
            options={
                'verbose_name': 'Quarantine Record',
                'verbose_name_plural': 'Quarantine Records',
                'ordering': ['-quarantined_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(db_index=True, max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Calculated quality score (0.0 to 100.0)', max_digits=5)),
                ('gap_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('is_stale', models.BooleanField(default=False)),
                ('hard_fail', models.BooleanField(default=False, help_text='If True, hard gate blocks all BUY_WINDOW signals')),
                ('anomalies', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Data Quality Snapshot',
                'verbose_name_plural': 'Data Quality Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='market_data_instrum_3892f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, help_text='Origin source exchange or feed ID (e.g. binance, okx, gold_reference)', max_length=32)),
                ('timeframe', models.CharField(db_index=True, help_text='Timeframe interval: 1m, 5m, 15m, 1h, 4h, 1d', max_length=8)),
                ('timestamp_open', models.DateTimeField(db_index=True)),
                ('timestamp_close', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('quote_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='USDT/USD conversion rate applied to this candle', max_digits=10)),
                ('close_usd', models.DecimalField(blank=True, decimal_places=8, help_text='Normalized USD price (close * quote_rate)', max_digits=18, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=True)),
                ('data_quality_flag', models.CharField(choices=[('OK', 'Good Quality'), ('SUSPECT', 'Suspect Data'), ('INTERPOLATED', 'Interpolated Missing Bar'), ('QUARANTINED', 'Quarantined Source')], db_index=True, default='OK', max_length=16)),
                ('source_sequence', models.BigIntegerField(blank=True, null=True)),
                ('ingestion_time', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='instruments.instrument')),
            ],
            options={
                'verbose_name': 'Market Candle',
                'verbose_name_plural': 'Market Candles',
                'ordering': ['timestamp_open'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'timestamp_open'], name='market_data_instrum_38a1f0_idx'), models.Index(fields=['instrument', 'timeframe', '-timestamp_open'], name='market_data_instrum_a6136b_idx'), models.Index(fields=['instrument', 'source', 'timeframe', 'timestamp_open'], name='market_data_instrum_3c1a2a_idx')],
                'unique_together': {('instrument', 'source', 'timeframe', 'timestamp_open')},
            },
        ),
    ]
