# Generated by Django 5.2.17 on 2026-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcandle',
            name='volume_evidence',
            field=models.CharField(choices=[('REAL_VOLUME', 'Real Volume'), ('TICK_VOLUME', 'Tick Volume'), ('PROXY_VOLUME', 'Proxy Volume'), ('UNAVAILABLE', 'Unavailable / Missing')], db_index=True, default='UNAVAILABLE', help_text='Volume semantics evidence type (REAL_VOLUME, TICK_VOLUME, PROXY_VOLUME, UNAVAILABLE)', max_length=16),
        ),
    ]
