# Generated by Django 5.2.17 on 2026-09-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_marketcandle_volume_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroEventIdentity',
            fields=[
                ('identity_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_family', models.CharField(choices=[('US_CPI', 'US Consumer Price Index'), ('US_NFP', 'US Nonfarm Payrolls'), ('FOMC_RATE', 'Federal Open Market Committee Rate Decision')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(default='US', max_length=8)),
                ('impact', models.CharField(default='HIGH', max_length=16)),
                ('reporting_agency', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Macro Event Identity',
                'verbose_name_plural': 'Macro Event Identities',
                'ordering': ['identity_id'],
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('snapshot_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1024)),
                ('source_name', models.CharField(db_index=True, max_length=64)),
                ('first_retrieved_at', models.DateTimeField(db_index=True)),
                ('http_status', models.IntegerField(default=200)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('etag', models.CharField(blank=True, max_length=256)),
                ('last_modified_header', models.CharField(blank=True, max_length=128)),
                ('raw_payload_bytes_sha256', models.CharField(db_index=True, max_length=64)),
                ('raw_content', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source Snapshot',
                'verbose_name_plural': 'Source Snapshots',
                'ordering': ['-first_retrieved_at'],
                'indexes': [models.Index(fields=['source_name', 'first_retrieved_at'], name='market_data_source__00d14d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MacroScheduleVintage',
            fields=[
                ('vintage_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('reference_period', models.CharField(db_index=True, max_length=32)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('schedule_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=32)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('known_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='market_data.macroeventidentity')),
                ('supersedes_vintage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='market_data.macroschedulevintage')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='market_data.sourcesnapshot')),
            ],
            options={
                'verbose_name': 'Macro Schedule Vintage',
                'verbose_name_plural': 'Macro Schedule Vintages',
                'ordering': ['-known_at', '-vintage_id'],
            },
        ),
        migrations.CreateModel(
            name='MacroObservationVintage',
            fields=[
                ('vintage_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('reference_period', models.CharField(db_index=True, max_length=32)),
                ('revision_number', models.IntegerField(db_index=True, default=0)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('vintage_date', models.DateField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('source_published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('known_at', models.DateTimeField(db_index=True)),
                ('raw_value', models.CharField(blank=True, max_length=64)),
                ('level_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('derived_change_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='market_data.macroeventidentity')),
                ('revises_vintage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='market_data.macroobservationvintage')),
                ('schedule_vintage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='market_data.macroschedulevintage')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='market_data.sourcesnapshot')),
            ],
            options={
                'verbose_name': 'Macro Observation Vintage',
                'verbose_name_plural': 'Macro Observation Vintages',
                'ordering': ['-known_at', '-revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='macroschedulevintage',
            index=models.Index(fields=['event', 'reference_period', 'known_at'], name='market_data_event_i_43f27f_idx'),
        ),
        migrations.AddIndex(
            model_name='macroschedulevintage',
            index=models.Index(fields=['known_at'], name='market_data_known_a_cde0fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='macroschedulevintage',
            constraint=models.UniqueConstraint(fields=('event', 'reference_period', 'known_at'), name='unique_macro_schedule_vintage'),
        ),
        migrations.AddIndex(
            model_name='macroobservationvintage',
            index=models.Index(fields=['event', 'reference_period', 'revision_number'], name='market_data_event_i_a263ec_idx'),
        ),
        migrations.AddIndex(
            model_name='macroobservationvintage',
            index=models.Index(fields=['known_at', 'source_published_at'], name='market_data_known_a_809ad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='macroobservationvintage',
            constraint=models.UniqueConstraint(fields=('event', 'reference_period', 'revision_number'), name='unique_macro_observation_revision'),
        ),
    ]
