# Generated by Django 5.2.17 on 2026-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_macroeventidentity_sourcesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroobservationvintage',
            name='non_publication_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='macroobservationvintage',
            name='publication_status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('PUBLISHED_LATE_OR_BUNDLED', 'Published Late or Bundled'), ('OFFICIALLY_NOT_PUBLISHED', 'Officially Not Published'), ('MISSING_UNEXPLAINED', 'Missing Unexplained'), ('INVALID', 'Invalid')], db_index=True, default='PUBLISHED', max_length=32),
        ),
    ]
