# Generated by Django 5.2.17 on 2026-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_macroobservationvintage_non_publication_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroschedulevintage',
            name='announcing_release_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macroschedulevintage',
            name='announcing_release_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='macroschedulevintage',
            name='parser_rule_version',
            field=models.CharField(default='BLS_PREVIOUS_RELEASE_V1', max_length=64),
        ),
        migrations.AddField(
            model_name='macroschedulevintage',
            name='provenance_type',
            field=models.CharField(choices=[('BLS_PREVIOUS_RELEASE_ANNOUNCEMENT', 'BLS Previous Release Announcement'), ('OMB_PFEI_SCHEDULE', 'OMB PFEI Schedule'), ('OTHER_FIRST_PARTY', 'Other First Party'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=48),
        ),
        migrations.AddIndex(
            model_name='macroschedulevintage',
            index=models.Index(fields=['provenance_type'], name='market_data_provena_2fba7e_idx'),
        ),
    ]
