# Generated by Django 5.2.17 on 2026-09-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_macroschedulevintage_announcing_release_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroScheduleProvenanceAssertion',
            fields=[
                ('assertion_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provenance_type', models.CharField(choices=[('BLS_PREVIOUS_RELEASE_ANNOUNCEMENT', 'BLS Previous Release Announcement'), ('OMB_PFEI_SCHEDULE', 'OMB PFEI Schedule'), ('OTHER_FIRST_PARTY', 'Other First Party'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=48)),
                ('announcing_release_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('announcing_release_timestamp', models.DateTimeField(blank=True, null=True)),
                ('parser_rule_version', models.CharField(default='PROVENANCE_RULE_V1', max_length=64)),
                ('asserted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_vintage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenance_assertions', to='market_data.macroschedulevintage')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_assertions', to='market_data.sourcesnapshot')),
                ('supersedes_assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='market_data.macroscheduleprovenanceassertion')),
            ],
            options={
                'verbose_name': 'Macro Schedule Provenance Assertion',
                'verbose_name_plural': 'Macro Schedule Provenance Assertions',
                'ordering': ['-asserted_at', '-assertion_id'],
                'indexes': [models.Index(fields=['schedule_vintage', 'provenance_type'], name='market_data_schedul_4c195e_idx'), models.Index(fields=['asserted_at'], name='market_data_asserte_272eef_idx')],
                'constraints': [models.UniqueConstraint(fields=('schedule_vintage', 'provenance_type', 'source_snapshot'), name='unique_schedule_provenance_assertion')],
            },
        ),
    ]
