# Generated by Django 5.2.17 on 2026-09-04 17:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_macroscheduleprovenanceassertion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrictionEvidenceDataset',
            fields=[
                ('dataset_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('account_tier', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('sample_start', models.DateTimeField(db_index=True)),
                ('sample_end', models.DateTimeField(db_index=True)),
                ('sample_count', models.IntegerField()),
                ('distinct_trading_days', models.IntegerField(default=1)),
                ('session_counts', models.JSONField(blank=True, default=dict)),
                ('source_units', models.CharField(max_length=32)),
                ('raw_dataset_sha256', models.CharField(db_index=True, max_length=64)),
                ('collection_methodology', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Friction Evidence Dataset',
                'verbose_name_plural': 'Friction Evidence Datasets',
                'ordering': ['-sample_end', '-dataset_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionModelVersion',
            fields=[
                ('model_version_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('account_tier', models.CharField(db_index=True, max_length=32)),
                ('legal_entity_code', models.CharField(db_index=True, max_length=64)),
                ('legal_entity_name', models.CharField(max_length=128)),
                ('regulator', models.CharField(max_length=64)),
                ('license_number', models.CharField(max_length=64)),
                ('digits', models.IntegerField(default=2)),
                ('point_size', models.DecimalField(decimal_places=5, default=Decimal('0.01'), max_digits=10)),
                ('trade_tick_size', models.DecimalField(decimal_places=5, default=Decimal('0.01'), max_digits=10)),
                ('trade_tick_value', models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=12)),
                ('contract_size', models.DecimalField(decimal_places=4, default=Decimal('100.0'), max_digits=12)),
                ('volume_min', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=10)),
                ('volume_max', models.DecimalField(decimal_places=4, default=Decimal('200.0'), max_digits=10)),
                ('volume_step', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=10)),
                ('native_commission_usd_per_lot_per_side', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('commission_formula', models.CharField(default='DYNAMIC_NOTIONAL_BPS', max_length=64)),
                ('swap_long_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('swap_short_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rollover_summer_utc_hour', models.IntegerField(default=21)),
                ('rollover_winter_utc_hour', models.IntegerField(default=22)),
                ('triple_swap_weekday', models.CharField(default='WEDNESDAY', max_length=16)),
                ('swap_free_available_for_account_type', models.BooleanField(default=False)),
                ('actual_account_swap_free_status', models.BooleanField(default=False)),
                ('base_spread_bps', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stress_spread_bps', models.DecimalField(decimal_places=4, max_digits=8)),
                ('base_slippage_bps', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('stress_slippage_bps', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('friction_policy_schema_version', models.CharField(default='1.0.0', max_length=32)),
                ('distribution_algorithm_version', models.CharField(default='1.0.0', max_length=32)),
                ('normalization_version', models.CharField(default='1.0.0', max_length=32)),
                ('commission_formula_version', models.CharField(default='1.0.0', max_length=32)),
                ('financing_rule_version', models.CharField(default='1.0.0', max_length=32)),
                ('empirical_friction_evidence_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Friction Model Version',
                'verbose_name_plural': 'Friction Model Versions',
                'ordering': ['-created_at', '-model_version_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionDistributionSummary',
            fields=[
                ('summary_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('SPREAD', 'Spread'), ('SLIPPAGE', 'Slippage'), ('COMMISSION', 'Commission'), ('FINANCING', 'Financing / Swap'), ('CONTRACT_SPEC', 'Contract Specification')], db_index=True, max_length=32)),
                ('condition', models.CharField(choices=[('NORMAL', 'Normal Conditions'), ('STRESSED', 'Stressed / Volatile Conditions'), ('MACRO_BLACKOUT', 'Macroeconomic Blackout Window'), ('ALL', 'All Conditions')], default='ALL', max_length=32)),
                ('session', models.CharField(choices=[('ASIAN', 'Asian Session'), ('LONDON', 'London Session'), ('NEW_YORK', 'New York Session'), ('ROLLOVER', 'Daily Rollover Window'), ('ALL', 'All Sessions Combined')], default='ALL', max_length=32)),
                ('unit', models.CharField(default='BPS', max_length=32)),
                ('sample_count', models.IntegerField()),
                ('stat_min', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_p50', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_p75', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_p90', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_p95', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_p99', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_max', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_mean', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stat_std', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='market_data.frictionevidencedataset')),
            ],
            options={
                'verbose_name': 'Friction Distribution Summary',
                'verbose_name_plural': 'Friction Distribution Summaries',
                'ordering': ['-created_at', '-summary_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionModelSummaryBinding',
            fields=[
                ('binding_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('binding_role', models.CharField(choices=[('PRIMARY_SPREAD_SAMPLE', 'Primary Spread Sample Dataset'), ('STRESS_SPREAD_SAMPLE', 'Stress Spread Sample Dataset'), ('TELEMETRY_SAMPLE', 'Execution Telemetry Sample Dataset'), ('NORMAL_SPREAD_DISTRIBUTION', 'Normal Spread Distribution Summary'), ('STRESS_SPREAD_DISTRIBUTION', 'Stress Spread Distribution Summary'), ('SLIPPAGE_DISTRIBUTION', 'Slippage Distribution Summary')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution_summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_bindings', to='market_data.frictiondistributionsummary')),
                ('friction_model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_bindings', to='market_data.frictionmodelversion')),
            ],
            options={
                'verbose_name': 'Friction Model Summary Binding',
                'verbose_name_plural': 'Friction Model Summary Bindings',
                'ordering': ['-created_at', '-binding_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionModelDatasetBinding',
            fields=[
                ('binding_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('binding_role', models.CharField(choices=[('PRIMARY_SPREAD_SAMPLE', 'Primary Spread Sample Dataset'), ('STRESS_SPREAD_SAMPLE', 'Stress Spread Sample Dataset'), ('TELEMETRY_SAMPLE', 'Execution Telemetry Sample Dataset'), ('NORMAL_SPREAD_DISTRIBUTION', 'Normal Spread Distribution Summary'), ('STRESS_SPREAD_DISTRIBUTION', 'Stress Spread Distribution Summary'), ('SLIPPAGE_DISTRIBUTION', 'Slippage Distribution Summary')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_bindings', to='market_data.frictionevidencedataset')),
                ('friction_model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_bindings', to='market_data.frictionmodelversion')),
            ],
            options={
                'verbose_name': 'Friction Model Dataset Binding',
                'verbose_name_plural': 'Friction Model Dataset Bindings',
                'ordering': ['-created_at', '-binding_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionModelActivation',
            fields=[
                ('activation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('known_at', models.DateTimeField(db_index=True)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('activation_status', models.CharField(choices=[('ACTIVE', 'Active Calibration Model'), ('SUPERSEDED', 'Superseded by Newer Calibration Model'), ('REJECTED', 'Rejected by Governance Evaluation'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=32)),
                ('source_or_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='market_data.frictionmodelactivation')),
                ('friction_model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='market_data.frictionmodelversion')),
            ],
            options={
                'verbose_name': 'Friction Model Activation',
                'verbose_name_plural': 'Friction Model Activations',
                'ordering': ['-effective_from', '-activation_id'],
            },
        ),
        migrations.CreateModel(
            name='FrictionSourceSnapshot',
            fields=[
                ('snapshot_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1024)),
                ('source_name', models.CharField(db_index=True, max_length=64)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('account_tier', models.CharField(db_index=True, max_length=32)),
                ('retrieved_at', models.DateTimeField(db_index=True)),
                ('known_at', models.DateTimeField(db_index=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.IntegerField(default=200)),
                ('raw_payload_bytes_sha256', models.CharField(db_index=True, max_length=64)),
                ('raw_content', models.BinaryField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Friction Source Snapshot',
                'verbose_name_plural': 'Friction Source Snapshots',
                'ordering': ['-known_at', '-snapshot_id'],
                'indexes': [models.Index(fields=['venue', 'symbol', 'account_tier'], name='market_data_venue_e72a74_idx'), models.Index(fields=['raw_payload_bytes_sha256'], name='market_data_raw_pay_dc0525_idx')],
            },
        ),
        migrations.AddField(
            model_name='frictionmodelversion',
            name='contract_spec_source_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_spec_models', to='market_data.frictionsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='frictionmodelversion',
            name='fee_schedule_source_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedule_models', to='market_data.frictionsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='frictionmodelversion',
            name='legal_entity_source_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_models', to='market_data.frictionsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='frictionmodelversion',
            name='swap_spec_source_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='swap_spec_models', to='market_data.frictionsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='frictionevidencedataset',
            name='source_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='market_data.frictionsourcesnapshot'),
        ),
        migrations.AddIndex(
            model_name='frictiondistributionsummary',
            index=models.Index(fields=['component_type', 'condition', 'session'], name='market_data_compone_d817d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='frictionmodelsummarybinding',
            constraint=models.UniqueConstraint(fields=('friction_model_version', 'distribution_summary', 'binding_role'), name='unique_friction_model_summary_binding'),
        ),
        migrations.AddConstraint(
            model_name='frictionmodeldatasetbinding',
            constraint=models.UniqueConstraint(fields=('friction_model_version', 'evidence_dataset', 'binding_role'), name='unique_friction_model_dataset_binding'),
        ),
        migrations.AddIndex(
            model_name='frictionmodelactivation',
            index=models.Index(fields=['activation_status', 'effective_from'], name='market_data_activat_91e05e_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionmodelversion',
            index=models.Index(fields=['venue', 'symbol', 'account_tier'], name='market_data_venue_19c492_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionmodelversion',
            index=models.Index(fields=['empirical_friction_evidence_fingerprint'], name='market_data_empiric_20bbac_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionevidencedataset',
            index=models.Index(fields=['venue', 'symbol', 'account_tier'], name='market_data_venue_52aa07_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionevidencedataset',
            index=models.Index(fields=['raw_dataset_sha256'], name='market_data_raw_dat_5b0bb5_idx'),
        ),
    ]
