# Generated by Django 5.2.17 on 2026-09-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0007_friction_evidence_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frictiondistributionsummary',
            name='condition',
            field=models.CharField(choices=[('NORMAL', 'Normal Conditions'), ('STRESSED', 'Stressed / Volatile Conditions'), ('MACRO_BLACKOUT', 'Macroeconomic Blackout Window'), ('ALL', 'All Conditions')], max_length=32),
        ),
        migrations.AlterField(
            model_name='frictiondistributionsummary',
            name='session',
            field=models.CharField(choices=[('ASIAN', 'Asian Session'), ('LONDON', 'London Session'), ('NEW_YORK', 'New York Session'), ('ROLLOVER', 'Daily Rollover Window'), ('ALL', 'All Sessions Combined')], max_length=32),
        ),
        migrations.AlterField(
            model_name='frictiondistributionsummary',
            name='unit',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='frictionevidencedataset',
            name='distinct_trading_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='frictionmodelactivation',
            name='activation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft Model (Evidence Incomplete / Unsealed)'), ('CANDIDATE', 'Candidate Model Awaiting Sign-Off'), ('ACTIVE', 'Active Calibration Model'), ('SUPERSEDED', 'Superseded by Newer Calibration Model'), ('REJECTED', 'Rejected by Governance Evaluation'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='frictionmodeldatasetbinding',
            name='binding_role',
            field=models.CharField(choices=[('PRIMARY_SPREAD_SAMPLE', 'Primary Spread Sample Dataset'), ('STRESS_SPREAD_SAMPLE', 'Stress Spread Sample Dataset'), ('TELEMETRY_SAMPLE', 'Execution Telemetry Sample Dataset'), ('PRIMARY_TELEMETRY_SAMPLE', 'Primary Execution Telemetry Sample Dataset'), ('NORMAL_SPREAD_DISTRIBUTION', 'Normal Spread Distribution Summary'), ('STRESS_SPREAD_DISTRIBUTION', 'Stress Spread Distribution Summary'), ('SLIPPAGE_DISTRIBUTION', 'Slippage Distribution Summary'), ('NORMAL_SLIPPAGE_DISTRIBUTION', 'Normal Slippage Distribution Summary'), ('STRESS_SLIPPAGE_DISTRIBUTION', 'Stress Slippage Distribution Summary')], max_length=32),
        ),
        migrations.AlterField(
            model_name='frictionmodelsummarybinding',
            name='binding_role',
            field=models.CharField(choices=[('PRIMARY_SPREAD_SAMPLE', 'Primary Spread Sample Dataset'), ('STRESS_SPREAD_SAMPLE', 'Stress Spread Sample Dataset'), ('TELEMETRY_SAMPLE', 'Execution Telemetry Sample Dataset'), ('PRIMARY_TELEMETRY_SAMPLE', 'Primary Execution Telemetry Sample Dataset'), ('NORMAL_SPREAD_DISTRIBUTION', 'Normal Spread Distribution Summary'), ('STRESS_SPREAD_DISTRIBUTION', 'Stress Spread Distribution Summary'), ('SLIPPAGE_DISTRIBUTION', 'Slippage Distribution Summary'), ('NORMAL_SLIPPAGE_DISTRIBUTION', 'Normal Slippage Distribution Summary'), ('STRESS_SLIPPAGE_DISTRIBUTION', 'Stress Slippage Distribution Summary')], max_length=32),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='actual_account_swap_free_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='base_spread_bps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='commission_formula',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='contract_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='digits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='native_commission_usd_per_lot_per_side',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='point_size',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='rollover_summer_utc_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='rollover_winter_utc_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='stress_spread_bps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='swap_free_available_for_account_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='swap_long_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='swap_short_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='trade_tick_size',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='trade_tick_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='triple_swap_weekday',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='volume_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='volume_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='volume_step',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='frictionmodelversion',
            name='empirical_friction_evidence_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
