# Generated by Django 5.2.17 on 2026-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0008_harden_friction_evidence_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='frictionmodelversion',
            name='slippage_cost_policy_version',
            field=models.CharField(default='ADVERSE_ONLY_P75_P95_V1', max_length=32),
        ),
        migrations.AddField(
            model_name='frictionsourcesnapshot',
            name='collection_methodology',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='frictionsourcesnapshot',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='frictionsourcesnapshot',
            name='source_origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='frictionsourcesnapshot',
            name='source_type',
            field=models.CharField(choices=[('OFFICIAL_BROKER_DOCUMENT', 'Official Broker Document'), ('MT5_SYMBOL_INFO_EXPORT', 'MT5 Symbol Info Export'), ('MT5_ACCOUNT_EXPORT', 'MT5 Account Export'), ('BROKER_PERSONAL_AREA_EXPORT', 'Broker Personal Area Export'), ('ACCOUNT_CLIENT_AGREEMENT', 'Account Client Agreement'), ('USER_PROVIDED_UNVERIFIED', 'User Provided Unverified')], db_index=True, default='USER_PROVIDED_UNVERIFIED', max_length=64),
        ),
    ]
