# Generated by Django 5.2.17 on 2026-09-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0009_frictionmodelversion_slippage_cost_policy_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frictiondistributionsummary',
            name='population_semantics',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown / Legacy Unspecified'), ('SPREAD_BPS', 'Spread Distribution (BPS)'), ('SLIPPAGE_ADVERSE_ONLY', 'Slippage Adverse-Only Distribution (BPS)'), ('SLIPPAGE_SIGNED', 'Slippage Raw Signed Distribution (BPS)')], db_index=True, default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='frictionsourcesnapshot',
            name='source_type',
            field=models.CharField(choices=[('OFFICIAL_BROKER_DOCUMENT', 'Official Broker Document'), ('MT5_SYMBOL_INFO_EXPORT', 'MT5 Symbol Info Export'), ('MT5_ACCOUNT_EXPORT', 'MT5 Account Export'), ('BROKER_PERSONAL_AREA_EXPORT', 'Broker Personal Area Export'), ('ACCOUNT_CLIENT_AGREEMENT', 'Account Client Agreement'), ('MT5_TICK_HISTORY_EXPORT', 'MT5 Tick History Export'), ('MT5_EXECUTION_TELEMETRY_EXPORT', 'MT5 Execution Telemetry Export'), ('USER_PROVIDED_UNVERIFIED', 'User Provided Unverified')], db_index=True, default='USER_PROVIDED_UNVERIFIED', max_length=64),
        ),
    ]
