# Generated by Django 5.2.17 on 2026-09-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0010_frictiondistributionsummary_population_semantics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frictionmodelversion',
            name='parser_version',
            field=models.CharField(default='1.0.0', max_length=32),
        ),
        migrations.CreateModel(
            name='FrictionSourceQualificationAssertion',
            fields=[
                ('assertion_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('component_role', models.CharField(db_index=True, max_length=32)),
                ('qualification_status', models.CharField(choices=[('QUALIFIED', 'Qualified Broker Evidence'), ('UNVERIFIED', 'Unverified / Format Only'), ('REJECTED', 'Rejected by Parser Validation')], db_index=True, default='UNVERIFIED', max_length=32)),
                ('parser_name', models.CharField(max_length=64)),
                ('parser_version', models.CharField(default='1.0.0', max_length=32)),
                ('raw_artifact_sha256', models.CharField(max_length=64)),
                ('normalized_evidence_hash', models.CharField(max_length=64)),
                ('asserted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('qualification_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_assertions', to='market_data.frictionsourcesnapshot')),
            ],
            options={
                'verbose_name': 'Friction Source Qualification Assertion',
                'verbose_name_plural': 'Friction Source Qualification Assertions',
                'ordering': ['-asserted_at', '-assertion_id'],
                'indexes': [models.Index(fields=['component_role', 'qualification_status'], name='market_data_compone_d913bd_idx'), models.Index(fields=['asserted_at'], name='market_data_asserte_a16d33_idx')],
            },
        ),
    ]
