# Generated by Django 5.2.17 on 2026-09-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0011_frictionmodelversion_parser_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrictionSourceProvenanceAttestation',
            fields=[
                ('attestation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('component_role', models.CharField(db_index=True, max_length=32)),
                ('source_origin', models.CharField(max_length=1024)),
                ('source_type', models.CharField(max_length=64)),
                ('collection_methodology', models.CharField(max_length=128)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('MT5_DIRECT_EXPORT', 'MT5 Direct Export'), ('BROKER_OFFICIAL_URL_CAPTURE', 'Broker Official URL Capture'), ('ACCOUNT_PORTAL_EXPORT', 'Account Portal Export'), ('MANUAL_REVIEWED_OFFICIAL_DOCUMENT', 'Manual Reviewed Official Document')], db_index=True, max_length=64)),
                ('verifier_identity', models.CharField(max_length=128)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('account_tier', models.CharField(db_index=True, max_length=32)),
                ('raw_artifact_sha256', models.CharField(db_index=True, max_length=64)),
                ('provenance_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenance_attestations', to='market_data.frictionsourcesnapshot')),
            ],
            options={
                'verbose_name': 'Friction Source Provenance Attestation',
                'verbose_name_plural': 'Friction Source Provenance Assertions',
                'ordering': ['-captured_at', '-attestation_id'],
            },
        ),
        migrations.AddField(
            model_name='frictionsourcequalificationassertion',
            name='provenance_attestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_assertions', to='market_data.frictionsourceprovenanceattestation'),
        ),
        migrations.AddIndex(
            model_name='frictionsourceprovenanceattestation',
            index=models.Index(fields=['component_role', 'raw_artifact_sha256'], name='market_data_compone_52eea7_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionsourceprovenanceattestation',
            index=models.Index(fields=['venue', 'symbol', 'account_tier'], name='market_data_venue_601453_idx'),
        ),
        migrations.AddIndex(
            model_name='frictionsourceprovenanceattestation',
            index=models.Index(fields=['verification_method'], name='market_data_verific_035f96_idx'),
        ),
    ]
