# Generated by Django 5.2.17 on 2026-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0012_frictionsourceprovenanceattestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frictionsourceprovenanceattestation',
            name='attestation_status',
            field=models.CharField(choices=[('DECLARED', 'Declared (Unverified Submission)'), ('VERIFIED', 'Verified (Authenticated Provenance Chain)'), ('REJECTED', 'Rejected (Failed Trust or Consistency Check)')], db_index=True, default='DECLARED', max_length=32),
        ),
        migrations.AddField(
            model_name='frictionsourceprovenanceattestation',
            name='verification_authority',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='frictionsourceprovenanceattestation',
            name='verification_proof',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='frictionsourceprovenanceattestation',
            name='verification_proof_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=32),
        ),
        migrations.AddIndex(
            model_name='frictionsourceprovenanceattestation',
            index=models.Index(fields=['attestation_status'], name='market_data_attesta_b1e8c7_idx'),
        ),
    ]
