# Generated by Django 5.2.17 on 2026-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0014_alter_frictionsourcesnapshot_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frictionsourceprovenanceattestation',
            name='verification_method',
            field=models.CharField(choices=[('MT5_DIRECT_EXPORT', 'MT5 Direct Export'), ('BROKER_OFFICIAL_URL_CAPTURE', 'Broker Official URL Capture'), ('ACCOUNT_PORTAL_EXPORT', 'Account Portal Export'), ('MANUAL_REVIEWED_OFFICIAL_DOCUMENT', 'Manual Reviewed Official Document'), ('COMPOSITE_GOVERNED_REVIEW', 'Composite Governed Review')], db_index=True, max_length=64),
        ),
    ]
