# Generated by Django 5.2.17 on 2026-08-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_alter_instrument_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_fingerprint', models.CharField(db_index=True, help_text='Deterministic SHA-256 hash of canonical production inputs', max_length=64, unique=True)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp of closed candle analyzed')),
                ('state', models.CharField(db_index=True, max_length=20)),
                ('user_decision', models.CharField(db_index=True, max_length=10)),
                ('direction_score', models.FloatField()),
                ('timing_score', models.FloatField()),
                ('reasons_positive', models.JSONField(default=list)),
                ('reasons_negative', models.JSONField(default=list)),
                ('hard_gate_reasons', models.JSONField(default=list)),
                ('components_breakdown', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('research_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('engine_version', models.CharField(default='4.0.0', max_length=30)),
                ('config_version', models.CharField(default='cfg-2026-v1', max_length=30)),
                ('feature_version', models.CharField(default='feat-2026-v1', max_length=30)),
                ('cycle_version', models.CharField(default='3.0.0-3A', max_length=30)),
                ('code_revision', models.CharField(default='2795de04', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_records', to='instruments.instrument')),
            ],
            options={
                'db_table': 'signal_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'timestamp'], name='signal_reco_instrum_c87963_idx'), models.Index(fields=['user_decision', 'state'], name='signal_reco_user_de_b53dfc_idx'), models.Index(fields=['config_version'], name='signal_reco_config__ad884c_idx')],
            },
        ),
    ]
