# Generated by Django 5.2.17 on 2026-08-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalrecord',
            name='code_revision',
            field=models.CharField(max_length=40),
        ),
    ]
