# Generated by Django on 2026-08-31 for Phase 4 XAUUSD Dual-Side Signal Engine

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_signalrecord_code_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalrecord',
            name='direction_score',
            field=models.FloatField(blank=True, help_text='Historical XAUT Direction score (0-100), NULL for XAUUSD', null=True),
        ),
        migrations.AlterField(
            model_name='signalrecord',
            name='timing_score',
            field=models.FloatField(blank=True, help_text='Historical XAUT Timing score (0-100), NULL for XAUUSD', null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='long_direction_score',
            field=models.FloatField(blank=True, help_text='Phase 4 XAUUSD Long Direction score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='short_direction_score',
            field=models.FloatField(blank=True, help_text='Phase 4 XAUUSD Short Direction score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='long_timing_score',
            field=models.FloatField(blank=True, help_text='Phase 4 XAUUSD Long Timing score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='short_timing_score',
            field=models.FloatField(blank=True, help_text='Phase 4 XAUUSD Short Timing score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='profile_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='calibration_status',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='resolution_reason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='phase4_policy_fingerprint',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
