# Generated by Django 5.2.17 on 2026-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMonitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(db_index=True, help_text='Canonical instrument symbol (e.g. XAUT/USDT)', max_length=32, unique=True)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('current_ask', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('spread_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('quote_source_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quote_received_timestamp', models.DateTimeField(blank=True, null=True)),
                ('quote_age_seconds', models.FloatField(blank=True, null=True)),
                ('is_quote_stale', models.BooleanField(default=False)),
                ('quote_sequence', models.BigIntegerField(blank=True, null=True)),
                ('entry_zone_status', models.CharField(db_index=True, default='NO_ACTIVE_ZONE', help_text='INSIDE_ZONE, ABOVE_ZONE, BELOW_ZONE, NO_ACTIVE_ZONE', max_length=32)),
                ('distance_to_entry_zone_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('last_closed_candle_ts', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_analysis_timestamp', models.DateTimeField(blank=True, null=True)),
                ('signal_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('signal_state', models.CharField(db_index=True, default='NO_TRADE', max_length=32)),
                ('signal_user_decision', models.CharField(db_index=True, default='WAIT', max_length=16)),
                ('direction_score', models.FloatField(default=0.0)),
                ('timing_score', models.FloatField(default=0.0)),
                ('risk_plan_valid', models.BooleanField(default=False)),
                ('execution_eligible', models.BooleanField(default=False)),
                ('effective_action', models.CharField(db_index=True, default='WAIT', help_text='Primary user-facing operational decision: BUY, WAIT, AVOID', max_length=16)),
                ('entry_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('entry_mid', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('entry_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('stop_final', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tp1', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('rr_tp1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rr_tp2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('reasons_positive', models.JSONField(blank=True, default=list)),
                ('reasons_negative', models.JSONField(blank=True, default=list)),
                ('hard_gate_reasons', models.JSONField(blank=True, default=list)),
                ('feed_health_data', models.JSONField(blank=True, default=dict)),
                ('engine_version', models.CharField(default='4.0.0', max_length=32)),
                ('config_version', models.CharField(default='cfg-2026-v1', max_length=32)),
                ('feature_version', models.CharField(default='feat-2026-v1', max_length=32)),
                ('cycle_version', models.CharField(default='3.0.0-3A', max_length=32)),
                ('risk_version', models.CharField(default='5.0.0', max_length=32)),
                ('code_revision', models.CharField(default='15d388d1', max_length=40)),
                ('decision_sequence', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Live Monitor State',
                'verbose_name_plural': 'Live Monitor States',
                'db_table': 'live_monitor_states',
            },
        ),
        migrations.CreateModel(
            name='LiveRiskPlanRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_signal_fingerprint', models.CharField(db_index=True, help_text='SHA-256 fingerprint of the triggering Phase 4 SignalRecord', max_length=64, unique=True)),
                ('signal_timestamp', models.DateTimeField(db_index=True)),
                ('instrument', models.CharField(db_index=True, max_length=32)),
                ('entry_min', models.DecimalField(decimal_places=4, max_digits=18)),
                ('entry_mid', models.DecimalField(decimal_places=4, max_digits=18)),
                ('entry_max', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_structure', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_atr', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_final', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_distance_atr', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tp1', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tp2', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rr_tp1', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rr_tp2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('is_valid_risk_plan', models.BooleanField(db_index=True)),
                ('execution_eligible', models.BooleanField(db_index=True)),
                ('effective_action', models.CharField(db_index=True, max_length=16)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('source_zone_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_zone_timestamp', models.DateTimeField(blank=True, null=True)),
                ('risk_version', models.CharField(default='5.0.0', max_length=32)),
                ('execution_model_version', models.CharField(default='5.0.0-exec-v1', max_length=32)),
                ('config_version', models.CharField(default='cfg-2026-v1', max_length=32)),
                ('code_revision', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_risk_plan_records',
                'ordering': ['-signal_timestamp'],
                'indexes': [models.Index(fields=['instrument', '-signal_timestamp'], name='live_risk_p_instrum_ddac9f_idx'), models.Index(fields=['effective_action'], name='live_risk_p_effecti_b2510c_idx'), models.Index(fields=['is_valid_risk_plan', 'execution_eligible'], name='live_risk_p_is_vali_43299b_idx')],
            },
        ),
    ]
