# Generated by Django 5.2.17 on 2026-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemonitorstate',
            name='analysis_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='calibration_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='candidate_effective_action',
            field=models.CharField(blank=True, help_text='Layer A effective action (BUY, SELL, WAIT)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='candidate_resolution_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='candidate_state',
            field=models.CharField(blank=True, db_index=True, help_text='Phase 4 Layer A candidate state (BUY_WINDOW, SELL_WINDOW, WAIT, CONFLICT, NO_TRADE)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='candidate_user_decision',
            field=models.CharField(blank=True, db_index=True, help_text='Phase 4 Layer A candidate decision (BUY, SELL, WAIT)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='long_direction_score',
            field=models.FloatField(blank=True, help_text='XAUUSD Long Direction Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='long_timing_score',
            field=models.FloatField(blank=True, help_text='XAUUSD Long Timing Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='phase4_policy_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='profile_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='publication_effective_action',
            field=models.CharField(blank=True, help_text='Layer B effective action (always WAIT in Phase 7)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='publication_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='published_state',
            field=models.CharField(blank=True, db_index=True, help_text='Phase 4 Layer B published state (from snapshot.state)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='published_user_decision',
            field=models.CharField(blank=True, db_index=True, help_text='Phase 4 Layer B published decision (WAIT while unauthorized)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='risk_candidate_status',
            field=models.CharField(blank=True, help_text='e.g. VALID, INVALID_GEOMETRY, NO_CANDIDATE', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='risk_plan_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='risk_side',
            field=models.CharField(blank=True, help_text='LONG or SHORT for active risk plan', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='short_direction_score',
            field=models.FloatField(blank=True, help_text='XAUUSD Short Direction Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='short_timing_score',
            field=models.FloatField(blank=True, help_text='XAUUSD Short Timing Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='source_phase4_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='stop_atr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='stop_distance_atr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='livemonitorstate',
            name='stop_structure',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='candidate_effective_action',
            field=models.CharField(blank=True, help_text='Layer A: BUY, SELL, or WAIT', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='entry_zone_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='phase5_policy_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='publication_effective_action',
            field=models.CharField(blank=True, help_text='Layer B: always WAIT in Phase 7', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='risk_candidate_status',
            field=models.CharField(blank=True, help_text='Risk candidate evaluation status', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='risk_candidate_valid',
            field=models.BooleanField(blank=True, help_text='True if risk plan geometry is valid', null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='risk_plan_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='risk_side',
            field=models.CharField(blank=True, help_text='LONG or SHORT', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='simulation_eligible',
            field=models.BooleanField(blank=True, help_text='True if simulation/execution eligible', null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='source_phase4_fingerprint',
            field=models.CharField(blank=True, help_text='Alias for source_signal_fingerprint for side-aware records', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='tp1_zone_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='liveriskplanrecord',
            name='tp2_zone_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='livemonitorstate',
            name='direction_score',
            field=models.FloatField(default=0.0, help_text='Historical XAUT single direction score, NULL for XAUUSD'),
        ),
        migrations.AlterField(
            model_name='livemonitorstate',
            name='instrument',
            field=models.CharField(db_index=True, help_text='Canonical instrument symbol (e.g. XAUUSD, XAUT/USDT)', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='livemonitorstate',
            name='timing_score',
            field=models.FloatField(default=0.0, help_text='Historical XAUT single timing score, NULL for XAUUSD'),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='entry_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='entry_mid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='entry_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='rr_tp1',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Alias for planned_rr_tp1', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='rr_tp2',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Alias for planned_rr_tp2', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='stop_atr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='stop_distance_atr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='stop_final',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='stop_structure',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='tp1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='tp2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='liveriskplanrecord',
            index=models.Index(fields=['risk_side'], name='live_risk_p_risk_si_fd7a27_idx'),
        ),
    ]
