# Generated by Django 5.2.17 on 2026-09-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_monitor', '0002_livemonitorstate_analysis_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='risk_plan_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Immutable unique identity of the Phase 5 Risk Plan', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='liveriskplanrecord',
            name='source_signal_fingerprint',
            field=models.CharField(db_index=True, help_text='SHA-256 fingerprint of the triggering Phase 4 SignalRecord', max_length=64),
        ),
    ]
