# Generated by Django 5.2.17 on 2026-09-11 08:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_monitor', '0003_alter_liveriskplanrecord_risk_plan_fingerprint_and_more'),
        ('signals', '0003_signalrecord_dual_side_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase8InterruptionRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_operational_failure', models.BooleanField(default=False)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phase8_interruption_records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Phase8OperationalState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='NOT_STARTED', help_text='NOT_STARTED, OBSERVING, INTERRUPTED, COMPLETE', max_length=20)),
                ('observation_window_start', models.DateTimeField(blank=True, null=True)),
                ('observation_day', models.IntegerField(default=0, help_text='Day index (1..14)')),
                ('completed_calendar_days', models.IntegerField(default=0)),
                ('last_successful_evaluation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('total_signals_evaluated', models.BigIntegerField(default=0)),
                ('buy_count', models.BigIntegerField(default=0)),
                ('sell_count', models.BigIntegerField(default=0)),
                ('no_trade_count', models.BigIntegerField(default=0)),
                ('paper_positions_opened', models.BigIntegerField(default=0)),
                ('paper_positions_closed', models.BigIntegerField(default=0)),
                ('outcomes_pending', models.BigIntegerField(default=0)),
                ('outcomes_resolved', models.BigIntegerField(default=0)),
                ('runtime_errors_count', models.BigIntegerField(default=0)),
                ('unresolved_integrity_failures', models.BigIntegerField(default=0)),
                ('data_freshness_status', models.CharField(default='UNKNOWN', max_length=32)),
                ('live_replay_parity_status', models.CharField(default='PENDING', max_length=20)),
                ('paper_only', models.BooleanField(default=True)),
                ('real_order_execution', models.CharField(default='disabled', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phase8_operational_state',
            },
        ),
        migrations.CreateModel(
            name='PaperObservationRecord',
            fields=[
                ('observation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('observation_fingerprint', models.CharField(db_index=True, help_text='Canonical SHA-256 reproducibility fingerprint', max_length=64, unique=True)),
                ('source_signal_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('source_risk_plan_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('instrument', models.CharField(db_index=True, default='XAUUSD', max_length=32)),
                ('broker_symbol', models.CharField(default='XAUUSDc', max_length=32)),
                ('side', models.CharField(db_index=True, help_text='BUY or SELL', max_length=10)),
                ('decision_timeframe', models.CharField(db_index=True, help_text='15m, 1h, 4h, 1d', max_length=10)),
                ('decision_timestamp', models.DateTimeField(db_index=True)),
                ('decision_candle_close', models.DateTimeField()),
                ('friction_model_version_id', models.CharField(db_index=True, default='EXNESS_XAUUSD_STANDARD_CENT_EMPIRICAL_V1', max_length=64)),
                ('friction_evidence_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('dataset_readiness_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('paper_entry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('paper_entry_price_basis', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spread_friction_applied', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('commission_friction_applied', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('financing_friction_applied', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('paper_exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('paper_exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('outcome', models.CharField(db_index=True, default='UNRESOLVED', max_length=32)),
                ('mfe_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mae_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gross_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('holding_duration_seconds', models.FloatField(blank=True, null=True)),
                ('paper_volume_lots', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pnl_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('gross_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('net_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('signal_decision', models.CharField(default='WAIT', max_length=16)),
                ('signal_score', models.FloatField(blank=True, null=True)),
                ('engine_version', models.CharField(default='4.0.0', max_length=32)),
                ('config_version', models.CharField(default='cfg-2026-v1', max_length=32)),
                ('code_revision', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_risk_plan_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_observations', to='live_monitor.liveriskplanrecord')),
                ('source_signal_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paper_observations', to='signals.signalrecord')),
            ],
            options={
                'db_table': 'phase8_paper_observation_records',
                'ordering': ['-decision_timestamp'],
                'indexes': [models.Index(fields=['instrument', '-decision_timestamp'], name='phase8_pape_instrum_2223d1_idx'), models.Index(fields=['side', 'outcome'], name='phase8_pape_side_849649_idx'), models.Index(fields=['decision_timeframe', 'side'], name='phase8_pape_decisio_dc4255_idx')],
            },
        ),
    ]
