# Generated by Django 5.2.17 on 2026-09-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_monitor', '0004_phase8interruptionrecord_phase8operationalstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase8operationalstate',
            name='duplicate_noop_cycles',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='eligible_cycles_expected',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='eligible_cycles_missing',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='eligible_cycles_observed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='expected_market_closure_cycles',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='last_expected_eligible_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase8operationalstate',
            name='last_processed_eligible_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
