# Generated by Django 5.2.17 on 2026-08-30 03:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_fingerprint', models.CharField(db_index=True, help_text='Canonical SHA-256 fingerprint of the backtest specification', max_length=64, unique=True)),
                ('instrument', models.CharField(db_index=True, default='XAUT/USDT', max_length=30)),
                ('dataset_identity', models.CharField(help_text='SHA-256 hash or identifier of historical dataset', max_length=64)),
                ('historical_start', models.DateTimeField(db_index=True)),
                ('historical_end', models.DateTimeField(db_index=True)),
                ('engine_version', models.CharField(default='4.0.0', max_length=30)),
                ('config_version', models.CharField(default='cfg-2026-v1', max_length=30)),
                ('feature_version', models.CharField(default='feat-2026-v1', max_length=30)),
                ('cycle_version', models.CharField(default='3.0.0-3A', max_length=30)),
                ('risk_version', models.CharField(default='5.0.0', max_length=30)),
                ('execution_model_version', models.CharField(default='5.0.0-exec-v1', max_length=30)),
                ('backtest_version', models.CharField(default='6.0.0', max_length=30)),
                ('code_revision', models.CharField(help_text='Git commit SHA or frozen baseline revision', max_length=40)),
                ('cost_config', models.JSONField(default=dict, help_text='Friction parameters (spread, fees, slippage)')),
                ('walkforward_config', models.JSONField(default=dict, help_text='Folds, ratios, purge, and embargo specifications')),
                ('purge_policy', models.CharField(default='EXACT_DEPENDENCY_PURGE', max_length=50)),
                ('embargo_policy', models.CharField(default='POST_BOUNDARY_BUFFER', max_length=50)),
                ('ablation_id', models.CharField(db_index=True, default='BASELINE', max_length=50)),
                ('aggregate_metrics', models.JSONField(default=dict, help_text='Funnel, expectancy, PF, and drawdown metrics')),
                ('temporal_stability', models.JSONField(default=dict, help_text='Cross-fold OOS stability and variance breakdown')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backtest_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument', 'ablation_id', 'created_at'], name='backtest_ru_instrum_003ef7_idx'), models.Index(fields=['status'], name='backtest_ru_status_48238d_idx'), models.Index(fields=['code_revision'], name='backtest_ru_code_re_3b4b98_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trade_id', models.CharField(db_index=True, max_length=64)),
                ('source_signal_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('signal_timestamp', models.DateTimeField(db_index=True)),
                ('dependency_end_timestamp', models.DateTimeField(db_index=True)),
                ('fill_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('outcome', models.CharField(db_index=True, max_length=30)),
                ('planned_risk_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gross_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gross_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mfe_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mae_r', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('exit_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('entry_spread', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('exit_spread', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('entry_slippage', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('exit_slippage', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=10)),
                ('fold_id', models.IntegerField(blank=True, null=True)),
                ('ambiguity_policy', models.CharField(default='LOWER_TIMEFRAME_REPLAY', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtests.backtestrun')),
            ],
            options={
                'db_table': 'backtest_trades',
                'ordering': ['signal_timestamp'],
                'indexes': [models.Index(fields=['backtest_run', 'outcome'], name='backtest_tr_backtes_e3424d_idx'), models.Index(fields=['signal_timestamp', 'dependency_end_timestamp'], name='backtest_tr_signal__dfc22a_idx')],
                'unique_together': {('backtest_run', 'trade_id')},
            },
        ),
    ]
