# Generated by Django 5.2.17 on 2026-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttrade',
            name='candidate_decision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='candidate_state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='execution_evidence_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='risk_plan_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='side',
            field=models.CharField(blank=True, db_index=True, default='LONG', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest_run', 'side'], name='backtest_tr_backtes_7c4b5a_idx'),
        ),
    ]
